version: '3'
services:
  guitar-tabs-editor:
    container_name: guitar-tabs-editor
    build: .
    ports:
      - '3000:3000'
    #volumes:
    #  - .:/app
    environment:
      - NODE_ENV=development
    command: npm start
